/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;



	public class DATATYPE_ROOM_INFO : DATATYPE_BASE
	{
		public ROOM_INFO createFromStreamEx(MemoryStream stream)
		{
			ROOM_INFO datas = new ROOM_INFO();
			datas.room_key = stream.readUint64();
			datas.player_count = stream.readUint8();
			datas.room_state = stream.readInt8();
			datas.room_creater = stream.readInt32();
			return datas;
		}

		public void addToStreamEx(Bundle stream, ROOM_INFO v)
		{
			stream.writeUint64(v.room_key);
			stream.writeUint8(v.player_count);
			stream.writeInt8(v.room_state);
			stream.writeInt32(v.room_creater);
		}
	}



	public class DATATYPE_ROOM_LIST : DATATYPE_BASE
	{
		private DATATYPE__ROOM_LIST_values_ArrayType_ChildArray values_DataType = new DATATYPE__ROOM_LIST_values_ArrayType_ChildArray();

		public class DATATYPE__ROOM_LIST_values_ArrayType_ChildArray : DATATYPE_BASE
		{
			private DATATYPE_ROOM_INFO itemType = new DATATYPE_ROOM_INFO();

			public List<ROOM_INFO> createFromStreamEx(MemoryStream stream)
			{
				UInt32 size = stream.readUint32();
				List<ROOM_INFO> datas = new List<ROOM_INFO>();

				while(size > 0)
				{
					--size;
					datas.Add(itemType.createFromStreamEx(stream));
				};

				return datas;
			}

			public void addToStreamEx(Bundle stream, List<ROOM_INFO> v)
			{
				stream.writeUint32((UInt32)v.Count);
				for(int i=0; i<v.Count; ++i)
				{
					itemType.addToStreamEx(stream, v[i]);
				};
			}
		}

		public ROOM_LIST createFromStreamEx(MemoryStream stream)
		{
			ROOM_LIST datas = new ROOM_LIST();
			datas.values = values_DataType.createFromStreamEx(stream);
			return datas;
		}

		public void addToStreamEx(Bundle stream, ROOM_LIST v)
		{
			values_DataType.addToStreamEx(stream, v.values);
		}
	}


}