/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[1] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_component1 = new Property();
			pAvatar_component1.name = "component1";
			pAvatar_component1.properUtype = 5;
			pAvatar_component1.properFlags = 253;
			pAvatar_component1.aliasID = 4;
			pAvatarModule.propertys["component1"] = pAvatar_component1; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_component1.aliasID] = pAvatar_component1;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(component1 / 5).");

			Property pAvatar_modelID = new Property();
			pAvatar_modelID.name = "modelID";
			pAvatar_modelID.properUtype = 3;
			pAvatar_modelID.properFlags = 4;
			pAvatar_modelID.aliasID = 5;
			Byte Avatar_modelID_defval;
			Byte.TryParse("0", out Avatar_modelID_defval);
			pAvatar_modelID.defaultVal = Avatar_modelID_defval;
			pAvatarModule.propertys["modelID"] = pAvatar_modelID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelID.aliasID] = pAvatar_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelID / 3).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 1;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 6;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 1).");

			pAvatarModule.useMethodDescrAlias = true;
			ScriptModule pOperationModule = new ScriptModule("Operation");
			EntityDef.moduledefs["Operation"] = pOperationModule;
			EntityDef.idmoduledefs[2] = pOperationModule;

			Property pOperation_position = new Property();
			pOperation_position.name = "position";
			pOperation_position.properUtype = 40000;
			pOperation_position.properFlags = 4;
			pOperation_position.aliasID = 1;
			Vector3 Operation_position_defval = new Vector3();
			pOperation_position.defaultVal = Operation_position_defval;
			pOperationModule.propertys["position"] = pOperation_position; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_position.aliasID] = pOperation_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(position / 40000).");

			Property pOperation_direction = new Property();
			pOperation_direction.name = "direction";
			pOperation_direction.properUtype = 40001;
			pOperation_direction.properFlags = 4;
			pOperation_direction.aliasID = 2;
			Vector3 Operation_direction_defval = new Vector3();
			pOperation_direction.defaultVal = Operation_direction_defval;
			pOperationModule.propertys["direction"] = pOperation_direction; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_direction.aliasID] = pOperation_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(direction / 40001).");

			Property pOperation_spaceID = new Property();
			pOperation_spaceID.name = "spaceID";
			pOperation_spaceID.properUtype = 40002;
			pOperation_spaceID.properFlags = 16;
			pOperation_spaceID.aliasID = 3;
			UInt32 Operation_spaceID_defval;
			UInt32.TryParse("", out Operation_spaceID_defval);
			pOperation_spaceID.defaultVal = Operation_spaceID_defval;
			pOperationModule.propertys["spaceID"] = pOperation_spaceID; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_spaceID.aliasID] = pOperation_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(spaceID / 40002).");

			Property pOperation_lossScore = new Property();
			pOperation_lossScore.name = "lossScore";
			pOperation_lossScore.properUtype = 7;
			pOperation_lossScore.properFlags = 16;
			pOperation_lossScore.aliasID = 4;
			Int32 Operation_lossScore_defval;
			Int32.TryParse("0", out Operation_lossScore_defval);
			pOperation_lossScore.defaultVal = Operation_lossScore_defval;
			pOperationModule.propertys["lossScore"] = pOperation_lossScore; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_lossScore.aliasID] = pOperation_lossScore;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(lossScore / 7).");

			Property pOperation_winScore = new Property();
			pOperation_winScore.name = "winScore";
			pOperation_winScore.properUtype = 6;
			pOperation_winScore.properFlags = 16;
			pOperation_winScore.aliasID = 5;
			Int32 Operation_winScore_defval;
			Int32.TryParse("0", out Operation_winScore_defval);
			pOperation_winScore.defaultVal = Operation_winScore_defval;
			pOperationModule.propertys["winScore"] = pOperation_winScore; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_winScore.aliasID] = pOperation_winScore;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(winScore / 6).");

			List<DATATYPE_BASE> pOperation_onCreateRoomResult_args = new List<DATATYPE_BASE>();
			pOperation_onCreateRoomResult_args.Add(EntityDef.id2datatypes[2]);
			pOperation_onCreateRoomResult_args.Add(EntityDef.id2datatypes[22]);

			Method pOperation_onCreateRoomResult = new Method();
			pOperation_onCreateRoomResult.name = "onCreateRoomResult";
			pOperation_onCreateRoomResult.methodUtype = 14;
			pOperation_onCreateRoomResult.aliasID = 1;
			pOperation_onCreateRoomResult.args = pOperation_onCreateRoomResult_args;

			pOperationModule.methods["onCreateRoomResult"] = pOperation_onCreateRoomResult; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onCreateRoomResult.aliasID] = pOperation_onCreateRoomResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onCreateRoomResult / 14).");

			List<DATATYPE_BASE> pOperation_onEnterRoomResult_args = new List<DATATYPE_BASE>();
			pOperation_onEnterRoomResult_args.Add(EntityDef.id2datatypes[2]);
			pOperation_onEnterRoomResult_args.Add(EntityDef.id2datatypes[22]);

			Method pOperation_onEnterRoomResult = new Method();
			pOperation_onEnterRoomResult.name = "onEnterRoomResult";
			pOperation_onEnterRoomResult.methodUtype = 11;
			pOperation_onEnterRoomResult.aliasID = 2;
			pOperation_onEnterRoomResult.args = pOperation_onEnterRoomResult_args;

			pOperationModule.methods["onEnterRoomResult"] = pOperation_onEnterRoomResult; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onEnterRoomResult.aliasID] = pOperation_onEnterRoomResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onEnterRoomResult / 11).");

			List<DATATYPE_BASE> pOperation_onGameBeginResult_args = new List<DATATYPE_BASE>();
			pOperation_onGameBeginResult_args.Add(EntityDef.id2datatypes[2]);

			Method pOperation_onGameBeginResult = new Method();
			pOperation_onGameBeginResult.name = "onGameBeginResult";
			pOperation_onGameBeginResult.methodUtype = 13;
			pOperation_onGameBeginResult.aliasID = 3;
			pOperation_onGameBeginResult.args = pOperation_onGameBeginResult_args;

			pOperationModule.methods["onGameBeginResult"] = pOperation_onGameBeginResult; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onGameBeginResult.aliasID] = pOperation_onGameBeginResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onGameBeginResult / 13).");

			List<DATATYPE_BASE> pOperation_onLeaveRoomResult_args = new List<DATATYPE_BASE>();
			pOperation_onLeaveRoomResult_args.Add(EntityDef.id2datatypes[2]);

			Method pOperation_onLeaveRoomResult = new Method();
			pOperation_onLeaveRoomResult.name = "onLeaveRoomResult";
			pOperation_onLeaveRoomResult.methodUtype = 12;
			pOperation_onLeaveRoomResult.aliasID = 4;
			pOperation_onLeaveRoomResult.args = pOperation_onLeaveRoomResult_args;

			pOperationModule.methods["onLeaveRoomResult"] = pOperation_onLeaveRoomResult; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onLeaveRoomResult.aliasID] = pOperation_onLeaveRoomResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onLeaveRoomResult / 12).");

			List<DATATYPE_BASE> pOperation_onReqRoomList_args = new List<DATATYPE_BASE>();
			pOperation_onReqRoomList_args.Add(EntityDef.id2datatypes[23]);

			Method pOperation_onReqRoomList = new Method();
			pOperation_onReqRoomList.name = "onReqRoomList";
			pOperation_onReqRoomList.methodUtype = 10;
			pOperation_onReqRoomList.aliasID = 5;
			pOperation_onReqRoomList.args = pOperation_onReqRoomList_args;

			pOperationModule.methods["onReqRoomList"] = pOperation_onReqRoomList; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onReqRoomList.aliasID] = pOperation_onReqRoomList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onReqRoomList / 10).");

			List<DATATYPE_BASE> pOperation_onTrueSyncData_args = new List<DATATYPE_BASE>();
			pOperation_onTrueSyncData_args.Add(EntityDef.id2datatypes[2]);
			pOperation_onTrueSyncData_args.Add(EntityDef.id2datatypes[12]);

			Method pOperation_onTrueSyncData = new Method();
			pOperation_onTrueSyncData.name = "onTrueSyncData";
			pOperation_onTrueSyncData.methodUtype = 15;
			pOperation_onTrueSyncData.aliasID = 6;
			pOperation_onTrueSyncData.args = pOperation_onTrueSyncData_args;

			pOperationModule.methods["onTrueSyncData"] = pOperation_onTrueSyncData; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onTrueSyncData.aliasID] = pOperation_onTrueSyncData;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onTrueSyncData / 15).");

			List<DATATYPE_BASE> pOperation_reqCreateRoom_args = new List<DATATYPE_BASE>();

			Method pOperation_reqCreateRoom = new Method();
			pOperation_reqCreateRoom.name = "reqCreateRoom";
			pOperation_reqCreateRoom.methodUtype = 8;
			pOperation_reqCreateRoom.aliasID = -1;
			pOperation_reqCreateRoom.args = pOperation_reqCreateRoom_args;

			pOperationModule.methods["reqCreateRoom"] = pOperation_reqCreateRoom; 
			pOperationModule.base_methods["reqCreateRoom"] = pOperation_reqCreateRoom;

			pOperationModule.idbase_methods[pOperation_reqCreateRoom.methodUtype] = pOperation_reqCreateRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqCreateRoom / 8).");

			List<DATATYPE_BASE> pOperation_reqEnterRoom_args = new List<DATATYPE_BASE>();
			pOperation_reqEnterRoom_args.Add(EntityDef.id2datatypes[5]);

			Method pOperation_reqEnterRoom = new Method();
			pOperation_reqEnterRoom.name = "reqEnterRoom";
			pOperation_reqEnterRoom.methodUtype = 6;
			pOperation_reqEnterRoom.aliasID = -1;
			pOperation_reqEnterRoom.args = pOperation_reqEnterRoom_args;

			pOperationModule.methods["reqEnterRoom"] = pOperation_reqEnterRoom; 
			pOperationModule.base_methods["reqEnterRoom"] = pOperation_reqEnterRoom;

			pOperationModule.idbase_methods[pOperation_reqEnterRoom.methodUtype] = pOperation_reqEnterRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqEnterRoom / 6).");

			List<DATATYPE_BASE> pOperation_reqGameBegin_args = new List<DATATYPE_BASE>();

			Method pOperation_reqGameBegin = new Method();
			pOperation_reqGameBegin.name = "reqGameBegin";
			pOperation_reqGameBegin.methodUtype = 9;
			pOperation_reqGameBegin.aliasID = -1;
			pOperation_reqGameBegin.args = pOperation_reqGameBegin_args;

			pOperationModule.methods["reqGameBegin"] = pOperation_reqGameBegin; 
			pOperationModule.base_methods["reqGameBegin"] = pOperation_reqGameBegin;

			pOperationModule.idbase_methods[pOperation_reqGameBegin.methodUtype] = pOperation_reqGameBegin;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqGameBegin / 9).");

			List<DATATYPE_BASE> pOperation_reqLeaveRoom_args = new List<DATATYPE_BASE>();

			Method pOperation_reqLeaveRoom = new Method();
			pOperation_reqLeaveRoom.name = "reqLeaveRoom";
			pOperation_reqLeaveRoom.methodUtype = 7;
			pOperation_reqLeaveRoom.aliasID = -1;
			pOperation_reqLeaveRoom.args = pOperation_reqLeaveRoom_args;

			pOperationModule.methods["reqLeaveRoom"] = pOperation_reqLeaveRoom; 
			pOperationModule.base_methods["reqLeaveRoom"] = pOperation_reqLeaveRoom;

			pOperationModule.idbase_methods[pOperation_reqLeaveRoom.methodUtype] = pOperation_reqLeaveRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqLeaveRoom / 7).");

			List<DATATYPE_BASE> pOperation_reqRoomList_args = new List<DATATYPE_BASE>();

			Method pOperation_reqRoomList = new Method();
			pOperation_reqRoomList.name = "reqRoomList";
			pOperation_reqRoomList.methodUtype = 5;
			pOperation_reqRoomList.aliasID = -1;
			pOperation_reqRoomList.args = pOperation_reqRoomList_args;

			pOperationModule.methods["reqRoomList"] = pOperation_reqRoomList; 
			pOperationModule.base_methods["reqRoomList"] = pOperation_reqRoomList;

			pOperationModule.idbase_methods[pOperation_reqRoomList.methodUtype] = pOperation_reqRoomList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqRoomList / 5).");

			List<DATATYPE_BASE> pOperation_reqTrueSyncData_args = new List<DATATYPE_BASE>();
			pOperation_reqTrueSyncData_args.Add(EntityDef.id2datatypes[2]);
			pOperation_reqTrueSyncData_args.Add(EntityDef.id2datatypes[12]);

			Method pOperation_reqTrueSyncData = new Method();
			pOperation_reqTrueSyncData.name = "reqTrueSyncData";
			pOperation_reqTrueSyncData.methodUtype = 4;
			pOperation_reqTrueSyncData.aliasID = -1;
			pOperation_reqTrueSyncData.args = pOperation_reqTrueSyncData_args;

			pOperationModule.methods["reqTrueSyncData"] = pOperation_reqTrueSyncData; 
			pOperationModule.cell_methods["reqTrueSyncData"] = pOperation_reqTrueSyncData;

			pOperationModule.idcell_methods[pOperation_reqTrueSyncData.methodUtype] = pOperation_reqTrueSyncData;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqTrueSyncData / 4).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "CMD_TYPE";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "SPACE_KEY";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "FRAMEID";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ENTITY_ID";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ROOM_INFO";
				DATATYPE_ROOM_INFO datatype = new DATATYPE_ROOM_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "ROOM_LIST";
				DATATYPE_ROOM_LIST datatype = new DATATYPE_ROOM_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "AnonymousArray_25";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}