/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Operation : OperationBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Operation.def
	public abstract class OperationBase : EntityComponent
	{
		public EntityBaseEntityCall_OperationBase baseEntityCall = null;
		public EntityCellEntityCall_OperationBase cellEntityCall = null;

		public Int32 lossScore = 0;
		public virtual void onLossScoreChanged(Int32 oldValue) {}
		public Int32 winScore = 0;
		public virtual void onWinScoreChanged(Int32 oldValue) {}

		public abstract void onCreateRoomResult(Byte arg1, ROOM_INFO arg2); 
		public abstract void onEnterRoomResult(Byte arg1, ROOM_INFO arg2); 
		public abstract void onGameBeginResult(Byte arg1); 
		public abstract void onLeaveRoomResult(Byte arg1); 
		public abstract void onReqRoomList(ROOM_LIST arg1); 
		public abstract void onTrueSyncData(Byte arg1, byte[] arg2);
        public abstract void onAttached();


        public override void createFromStream(MemoryStream stream)
		{
			base.createFromStream(stream);
			baseEntityCall = new EntityBaseEntityCall_OperationBase(entityComponentPropertyID, ownerID);
			cellEntityCall = new EntityCellEntityCall_OperationBase(entityComponentPropertyID, ownerID);
		}

		public override void onRemoteMethodCall(UInt16 methodUtype, MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Operation"];

			Method method = sm.idmethods[methodUtype];
			switch(method.methodUtype)
			{
				case 14:
					Byte onCreateRoomResult_arg1 = stream.readUint8();
					ROOM_INFO onCreateRoomResult_arg2 = ((DATATYPE_ROOM_INFO)method.args[1]).createFromStreamEx(stream);
					onCreateRoomResult(onCreateRoomResult_arg1, onCreateRoomResult_arg2);
					break;
				case 11:
					Byte onEnterRoomResult_arg1 = stream.readUint8();
					ROOM_INFO onEnterRoomResult_arg2 = ((DATATYPE_ROOM_INFO)method.args[1]).createFromStreamEx(stream);
					onEnterRoomResult(onEnterRoomResult_arg1, onEnterRoomResult_arg2);
					break;
				case 13:
					Byte onGameBeginResult_arg1 = stream.readUint8();
					onGameBeginResult(onGameBeginResult_arg1);
					break;
				case 12:
					Byte onLeaveRoomResult_arg1 = stream.readUint8();
					onLeaveRoomResult(onLeaveRoomResult_arg1);
					break;
				case 10:
					ROOM_LIST onReqRoomList_arg1 = ((DATATYPE_ROOM_LIST)method.args[0]).createFromStreamEx(stream);
					onReqRoomList(onReqRoomList_arg1);
					break;
				case 15:
					Byte onTrueSyncData_arg1 = stream.readUint8();
					byte[] onTrueSyncData_arg2 = stream.readBlob();
					onTrueSyncData(onTrueSyncData_arg1, onTrueSyncData_arg2);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(UInt16 propUtype, MemoryStream stream, int maxCount)
		{
			ScriptModule sm = EntityDef.moduledefs["Operation"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0 && maxCount-- != 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = propUtype;

				if(_t_child_utype == 0)
				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				prop = pdatas[_t_child_utype];

				switch(prop.properUtype)
				{
					case 7:
						Int32 oldval_lossScore = lossScore;
						lossScore = stream.readInt32();

						if(prop.isBase())
						{
							if(owner.inited)
								onLossScoreChanged(oldval_lossScore);
						}
						else
						{
							if(owner.inWorld)
								onLossScoreChanged(oldval_lossScore);
						}

						break;
					case 6:
						Int32 oldval_winScore = winScore;
						winScore = stream.readInt32();

						if(prop.isBase())
						{
							if(owner.inited)
								onWinScoreChanged(oldval_winScore);
						}
						else
						{
							if(owner.inWorld)
								onWinScoreChanged(oldval_winScore);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Operation"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Int32 oldval_lossScore = lossScore;
			Property prop_lossScore = pdatas[4];
			if(prop_lossScore.isBase())
			{
				if(owner.inited && !owner.inWorld)
					onLossScoreChanged(oldval_lossScore);
			}
			else
			{
				if(owner.inWorld)
				{
					if(prop_lossScore.isOwnerOnly() && !owner.isPlayer())
					{
					}
					else
					{
						onLossScoreChanged(oldval_lossScore);
					}
				}
			}

			Int32 oldval_winScore = winScore;
			Property prop_winScore = pdatas[5];
			if(prop_winScore.isBase())
			{
				if(owner.inited && !owner.inWorld)
					onWinScoreChanged(oldval_winScore);
			}
			else
			{
				if(owner.inWorld)
				{
					if(prop_winScore.isOwnerOnly() && !owner.isPlayer())
					{
					}
					else
					{
						onWinScoreChanged(oldval_winScore);
					}
				}
			}

		}
	}
}